title = "Gisela Rua"
baseURL = "/"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
address = "Washington, DC"
email = "gisela.rua@frb.gov"
favicon = "/favicon.ico"
firstName = "Gisela"
lastName = "Rua"
phone = "1-555-555-1234"
profileImage = "img/TechChat.png"
showEducation = true
showExperience = false
showOpenSource = false
showProjects = false
showPublications = true
showQr = false
showSkills = false

[params.google]

# [params.google.analytics]
# trackerID = "XX-123446-01"

# [[params.handles]]
# link = "https://www.linkedin.com/in/edwardwebb/"
# name = "LinkedIn"

# [[params.handles]]
# link = "https://github.com/eddiewebb/"
# name = "GitHub"

# [[params.handles]]
# link = "https://bitbucket.org/eddiewebb/"
# name = "Bitbucket"

# [[params.handles]]
# link = "https://stackoverflow.com/users/story/82880"
# name = "Stack Overflow"

# [[params.handles]]
# link = "https://keybase.io/edwardawebb"
# name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
